version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: coffee_break_postgres
    environment:
      POSTGRES_USER: coffee_break_postgres
      POSTGRES_PASSWORD: PgWUxw4xYcoUmPi
      POSTGRES_DB: coffee_break_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  coffee_break:
    build:
      context: .
    volumes:
      - postgres_data
    depends_on:
      - postgres

volumes:
  postgres_data:
